JV2016-GruposM/src/accesoUsr/UsrException.java
JV2016-GruposM/src/modelo/ModeloException.java
JV2016-GruposM/src/util/UtilException.java

Grupo: 0 - A. Juan Pérez
Se han añadido tres nuevos tipos de excepción en los paquetes .modelo, .util y .accesoUsr para la gestión de los errores.

Nuevos tipos de excepción en los paquetes .modelo, .util y .accesoUsr.

---

JV2016-GruposM/src/accesoDatos/DatosException.java

Nueva Exception para .accesoDatos.

Nueva Exception para .accesoDatos.

---

JV2016-GruposM/src/modelo/Usuario.java

Actualización de clase Usuario 2.1 con Exception.
David Olivera Jaén Grupo 2

Actualización de clase Usuario 2.1 con Exception

---

JV2016-GruposM/src/modelo/DireccionPostal.java

Se ha añadido excepciones a la clase DireccionPostal.java.
(Empecé a modificar la clase en la codificación por defecto de Windows, cuando me di cuenta lo pasé a UTF-8 pero hay partes de los comentarios no se han visto afectados por el cambio. Se prevé para un próximo PullResquet su arreglo)
Jesús Lopéz Corvalán Grupo 2

Prototipo 2.1 excepciones

---

JV2016-GruposM/src/modelo/Simulacion.java

Autor: Juan Diego Cerezo
Grupo: 1
Fecha: 03/05/2017
Cambios realizados: Se han implementado las excepciones pedidas en el apartado 2, además de algunas comprobaciones a través de assert y la conveniente modificación del clone.

Implementación de excepciones versión 2.1

---

JV2016-GruposM/src/modelo/test/UsuarioTest.java

Actualización de UsuarioTest 2.1

Actualización de UsuarioTest 2.1 

---

JV2016-GruposM/src/modelo/ClaveAcceso.java
JV2016-GruposM/src/modelo/Correo.java

Grupo 1: Francisco Javier Fernandez López
Se ha corregido y actualizado la clase ClaveAcceso

Corrección de ClaveAcceso

---

JV2016-GruposM/src/modelo/DireccionPostal.java
JV2016-GruposM/src/modelo/Patron.java

Se han añadido los asertos que faltaban en las validaciones, además de corregir los errores de texto producidos por abrir el proyecto en un entorno con una codificación incorrecta.
Jesús Lopéz Corvalán  Grupo 2 / Bloque 3 (Alejandro, David, Samuel, Ruben, Sandra)

Inclusion de assertos y arreglo de codificación. Version 2.1

---

JV2016-GruposM/src/accesoDatos/memoria/UsuariosDAO.java

Modificación Excepciones versión 2.1
Añadidas las excepciones: try, catch y throws
Alejandro Montoya Sánchez

Modificación Excepciones versión 2.1

---

JV2016-GruposM/src/modelo/Persona.java

Actualización Persona.java con Exceptions

---

JV2016-GruposM/src/modelo/Posicion.java
JV2016-GruposM/src/modelo/SesionUsuario.java

Modificación clase sesion de usuario y posicion.
Victor Ruiz Grupo 4

Modificación clase sesion de usuario y posicion.

---

JV2016-GruposM/jv.config
JV2016-GruposM/src/accesoDatos/Datos.java
JV2016-GruposM/src/accesoDatos/OperacionesDAO.java
JV2016-GruposM/src/accesoDatos/memoria/MundosDAO.java
JV2016-GruposM/src/accesoDatos/memoria/PatronesDAO.java
JV2016-GruposM/src/accesoDatos/memoria/SesionesDAO.java
JV2016-GruposM/src/accesoDatos/memoria/SimulacionesDAO.java
JV2016-GruposM/src/accesoDatos/memoria/UsuariosDAO.java
JV2016-GruposM/src/accesoDatos/test/CopyOfDatosTest.java
JV2016-GruposM/src/accesoDatos/test/DatosPrueba.java
JV2016-GruposM/src/accesoDatos/test/DatosTest.java
JV2016-GruposM/src/config/Configuracion.java

Grupo 0: AJP
Añade gestión de la configuración basada en Propertie
Actualiza DAO's de almacenamiento en memoria adaptados a la nueva
gestión de la configuración.
Se ajustan los datos de prueba en una clase dentro del paquete
accesoDatos.test

Añade gestión de la configuración basada en Propertie

---

JV2016-GruposM/src/modelo/test/CorreoTest.java
JV2016-GruposM/src/modelo/test/SimulacionTest.java

Grupo 1: Francisco Javier Fernández López
Implementación de las clases CorreoTest y SimulacionTest con sus correspondientes excepciones

Implementacion de las clases CorreoTest y SimulacionTest

---

JV2016-GruposM/src/modelo/test/UsuarioTest.java

Modificación datos no validos 2.1

Modificación datos no validos 2.1

---

JV2016-GruposM/src/JVPrincipal.java
JV2016-GruposM/src/accesoDatos/fichero/MundosDAO.java
JV2016-GruposM/src/accesoDatos/fichero/PatronesDAO.java
JV2016-GruposM/src/accesoDatos/fichero/Persistente.java
JV2016-GruposM/src/accesoDatos/fichero/SesionesDAO.java
JV2016-GruposM/src/accesoDatos/fichero/SimulacionesDAO.java
JV2016-GruposM/src/accesoDatos/fichero/UsuariosDAO.java
JV2016-GruposM/src/accesoDatos/test/DatosPrueba.java
JV2016-GruposM/src/accesoDatos/test/DatosTest.java
JV2016-GruposM/src/accesoUsr/VistaTexto/VistaSesionTexto.java
JV2016-GruposM/src/accesoUsr/control/ControlSesion.java
JV2016-GruposM/src/modelo/ClaveAcceso.java
JV2016-GruposM/src/modelo/Correo.java
JV2016-GruposM/src/modelo/DireccionPostal.java
JV2016-GruposM/src/modelo/Mundo.java
JV2016-GruposM/src/modelo/Nif.java
JV2016-GruposM/src/modelo/Patron.java
JV2016-GruposM/src/modelo/Posicion.java
JV2016-GruposM/src/modelo/SesionUsuario.java
JV2016-GruposM/src/modelo/Simulacion.java
JV2016-GruposM/src/modelo/Usuario.java
JV2016-GruposM/src/modelo/test/ClaveAccesoTest.java
JV2016-GruposM/src/modelo/test/NifTest.java
JV2016-GruposM/src/modelo/test/UsuarioTest.java
JV2016-GruposM/src/util/Fecha.java
JV2016-GruposM/src/util/Formato.java

Grupo 0: AJP
Añade MVC de inicio de sesion:
ControlSesion
VistaSesionTexto

Añade MVC de inicio de sesion: ControlSesion VistaSesionTexto

---

JV2016-GruposM/src/accesoDatos/fichero/SimulacionesDAO.java

Actualizacion de simulacionesDAO.

---

JV2016-GruposM/src/JVPrincipal.java

Grupo 0: AJP
Actualiza secuecia inicial de main() para utilizar el menú principal.

Actualiza secuecia inicial de main() para utilizar el menú principal.

---

JV2016-GruposM/src/accesoDatos/db4o/SimulacionesDAO.java

Juan Antonio Sánchez Alarcón Grupo nº1.

Implementacion de base de datos SimulacionesDAO.java

---

JV2016-GruposM/src/accesoDatos/db4o/UsuariosDAO.java

UsuariosDAO actualizado en db4o

UsuariosDAO actualizado en db4o

---

JV2016-GruposM/src/accesoDatos/db4o/PatronesDAO.java

Actualización PatronesDao

---

JV2016-GruposM/src/accesoDatos/OperacionesDAO.java
JV2016-GruposM/src/accesoDatos/fichero/PatronesDAO.java
JV2016-GruposM/src/accesoDatos/fichero/UsuariosDAO.java
JV2016-GruposM/src/accesoDatos/memoria/PatronesDAO.java
JV2016-GruposM/src/accesoDatos/memoria/SesionesDAO.java
JV2016-GruposM/src/accesoDatos/memoria/UsuariosDAO.java

Se actualiza la fachada OperacionesDAO incluyendo método para uso exclusivo de la clase PatronesDAO.
También se actualizan las clases afectadas de los paquetes memoria y fichero.
Jesus L C, Grupo 2

Se actualiza la fachada OperacionesDAO y las clases afectadas al cambio, relativas a los paquetes memoria y fichero.
